# Generated by Django 4.2.7 on 2023-11-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trains',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('price', models.FloatField(default=120)),
                ('seats_available', models.IntegerField()),
            ],
        ),
    ]
