# Generated by Django 4.2.7 on 2023-11-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20200608_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trains',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
